// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: gateways/grpc/service.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *IntItem) Reset() {
	*x = IntItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateways_grpc_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntItem) ProtoMessage() {}

func (x *IntItem) ProtoReflect() protoreflect.Message {
	mi := &file_gateways_grpc_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntItem.ProtoReflect.Descriptor instead.
func (*IntItem) Descriptor() ([]byte, []int) {
	return file_gateways_grpc_service_proto_rawDescGZIP(), []int{0}
}

func (x *IntItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IntItem) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type IntItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*IntItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *IntItems) Reset() {
	*x = IntItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateways_grpc_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntItems) ProtoMessage() {}

func (x *IntItems) ProtoReflect() protoreflect.Message {
	mi := &file_gateways_grpc_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntItems.ProtoReflect.Descriptor instead.
func (*IntItems) Descriptor() ([]byte, []int) {
	return file_gateways_grpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *IntItems) GetItems() []*IntItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TextItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TextItem) Reset() {
	*x = TextItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateways_grpc_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextItem) ProtoMessage() {}

func (x *TextItem) ProtoReflect() protoreflect.Message {
	mi := &file_gateways_grpc_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextItem.ProtoReflect.Descriptor instead.
func (*TextItem) Descriptor() ([]byte, []int) {
	return file_gateways_grpc_service_proto_rawDescGZIP(), []int{2}
}

func (x *TextItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TextItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TextItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*TextItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *TextItems) Reset() {
	*x = TextItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateways_grpc_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextItems) ProtoMessage() {}

func (x *TextItems) ProtoReflect() protoreflect.Message {
	mi := &file_gateways_grpc_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextItems.ProtoReflect.Descriptor instead.
func (*TextItems) Descriptor() ([]byte, []int) {
	return file_gateways_grpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *TextItems) GetItems() []*TextItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_gateways_grpc_service_proto protoreflect.FileDescriptor

var file_gateways_grpc_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73,
	0x6f, 0x72, 0x74, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x07, 0x49, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e,
	0x75, 0x6d, 0x22, 0x31, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x25,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x73, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x2e, 0x0a, 0x08, 0x54, 0x65, 0x78, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x33, 0x0a, 0x09, 0x54, 0x65, 0x78, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0x6e, 0x0a, 0x06, 0x53, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x08, 0x53, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x73,
	0x12, 0x10, 0x2e, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x1a, 0x10, 0x2e, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x53, 0x6f, 0x72, 0x74, 0x54, 0x65,
	0x78, 0x74, 0x12, 0x11, 0x2e, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x11, 0x2e, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x54,
	0x65, 0x78, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_gateways_grpc_service_proto_rawDescOnce sync.Once
	file_gateways_grpc_service_proto_rawDescData = file_gateways_grpc_service_proto_rawDesc
)

func file_gateways_grpc_service_proto_rawDescGZIP() []byte {
	file_gateways_grpc_service_proto_rawDescOnce.Do(func() {
		file_gateways_grpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateways_grpc_service_proto_rawDescData)
	})
	return file_gateways_grpc_service_proto_rawDescData
}

var file_gateways_grpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gateways_grpc_service_proto_goTypes = []interface{}{
	(*IntItem)(nil),   // 0: sorter.IntItem
	(*IntItems)(nil),  // 1: sorter.IntItems
	(*TextItem)(nil),  // 2: sorter.TextItem
	(*TextItems)(nil), // 3: sorter.TextItems
}
var file_gateways_grpc_service_proto_depIdxs = []int32{
	0, // 0: sorter.IntItems.items:type_name -> sorter.IntItem
	2, // 1: sorter.TextItems.items:type_name -> sorter.TextItem
	1, // 2: sorter.Sorter.SortInts:input_type -> sorter.IntItems
	3, // 3: sorter.Sorter.SortText:input_type -> sorter.TextItems
	1, // 4: sorter.Sorter.SortInts:output_type -> sorter.IntItems
	3, // 5: sorter.Sorter.SortText:output_type -> sorter.TextItems
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gateways_grpc_service_proto_init() }
func file_gateways_grpc_service_proto_init() {
	if File_gateways_grpc_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateways_grpc_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateways_grpc_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateways_grpc_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateways_grpc_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateways_grpc_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateways_grpc_service_proto_goTypes,
		DependencyIndexes: file_gateways_grpc_service_proto_depIdxs,
		MessageInfos:      file_gateways_grpc_service_proto_msgTypes,
	}.Build()
	File_gateways_grpc_service_proto = out.File
	file_gateways_grpc_service_proto_rawDesc = nil
	file_gateways_grpc_service_proto_goTypes = nil
	file_gateways_grpc_service_proto_depIdxs = nil
}
