// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SorterClient is the client API for Sorter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SorterClient interface {
	SortInts(ctx context.Context, in *IntItems, opts ...grpc.CallOption) (*IntItems, error)
	SortText(ctx context.Context, in *TextItems, opts ...grpc.CallOption) (*TextItems, error)
}

type sorterClient struct {
	cc grpc.ClientConnInterface
}

func NewSorterClient(cc grpc.ClientConnInterface) SorterClient {
	return &sorterClient{cc}
}

func (c *sorterClient) SortInts(ctx context.Context, in *IntItems, opts ...grpc.CallOption) (*IntItems, error) {
	out := new(IntItems)
	err := c.cc.Invoke(ctx, "/sorter.Sorter/SortInts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sorterClient) SortText(ctx context.Context, in *TextItems, opts ...grpc.CallOption) (*TextItems, error) {
	out := new(TextItems)
	err := c.cc.Invoke(ctx, "/sorter.Sorter/SortText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SorterServer is the server API for Sorter service.
// All implementations must embed UnimplementedSorterServer
// for forward compatibility
type SorterServer interface {
	SortInts(context.Context, *IntItems) (*IntItems, error)
	SortText(context.Context, *TextItems) (*TextItems, error)
	mustEmbedUnimplementedSorterServer()
}

// UnimplementedSorterServer must be embedded to have forward compatible implementations.
type UnimplementedSorterServer struct {
}

func (UnimplementedSorterServer) SortInts(context.Context, *IntItems) (*IntItems, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SortInts not implemented")
}
func (UnimplementedSorterServer) SortText(context.Context, *TextItems) (*TextItems, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SortText not implemented")
}
func (UnimplementedSorterServer) mustEmbedUnimplementedSorterServer() {}

// UnsafeSorterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SorterServer will
// result in compilation errors.
type UnsafeSorterServer interface {
	mustEmbedUnimplementedSorterServer()
}

func RegisterSorterServer(s grpc.ServiceRegistrar, srv SorterServer) {
	s.RegisterService(&Sorter_ServiceDesc, srv)
}

func _Sorter_SortInts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntItems)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SorterServer).SortInts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sorter.Sorter/SortInts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SorterServer).SortInts(ctx, req.(*IntItems))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sorter_SortText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextItems)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SorterServer).SortText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sorter.Sorter/SortText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SorterServer).SortText(ctx, req.(*TextItems))
	}
	return interceptor(ctx, in, info, handler)
}

// Sorter_ServiceDesc is the grpc.ServiceDesc for Sorter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sorter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sorter.Sorter",
	HandlerType: (*SorterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SortInts",
			Handler:    _Sorter_SortInts_Handler,
		},
		{
			MethodName: "SortText",
			Handler:    _Sorter_SortText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
